// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package configauditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigAuditorClient is the client API for ConfigAuditor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigAuditorClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type configAuditorClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigAuditorClient(cc grpc.ClientConnInterface) ConfigAuditorClient {
	return &configAuditorClient{cc}
}

func (c *configAuditorClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, "/configaudit.v1.ConfigAuditor/Analyze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAuditorServer is the server API for ConfigAuditor service.
// All implementations must embed UnimplementedConfigAuditorServer
// for forward compatibility
type ConfigAuditorServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedConfigAuditorServer()
}

// UnimplementedConfigAuditorServer must be embedded to have forward compatible implementations.
type UnimplementedConfigAuditorServer struct {
}

func (UnimplementedConfigAuditorServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedConfigAuditorServer) mustEmbedUnimplementedConfigAuditorServer() {}

// UnsafeConfigAuditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigAuditorServer will
// result in compilation errors.
type UnsafeConfigAuditorServer interface {
	mustEmbedUnimplementedConfigAuditorServer()
}

func RegisterConfigAuditorServer(s grpc.ServiceRegistrar, srv ConfigAuditorServer) {
	s.RegisterService(&ConfigAuditor_ServiceDesc, srv)
}

func _ConfigAuditor_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAuditorServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configaudit.v1.ConfigAuditor/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAuditorServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigAuditor_ServiceDesc is the grpc.ServiceDesc for ConfigAuditor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigAuditor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configaudit.v1.ConfigAuditor",
	HandlerType: (*ConfigAuditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _ConfigAuditor_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/configaudit/v1/auditor.proto",
}
